# Generated by Django 4.1.5 on 2023-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="listings",
            field=models.ManyToManyField(blank=True, to="auctions.listing"),
        ),
    ]
