# Generated by Django 4.1.5 on 2023-11-30 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_remove_comment_message_comment_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="text",
        ),
        migrations.AddField(
            model_name="comment",
            name="message",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
